CREATE TABLE `counselors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`counselorId` varchar(50) NOT NULL,
	`name` varchar(200) NOT NULL,
	`shortName` varchar(100),
	`nationality` varchar(100),
	`birthYear` int,
	`deathYear` int,
	`photoUrl` text,
	`shortBio` text,
	`fullBio` text,
	`mainTheory` varchar(200),
	`keyContributions` json,
	`areasOfExpertise` json,
	`mainBooks` json,
	`articles` json,
	`otherMaterials` json,
	`personalityTraits` json,
	`writingStyle` text,
	`analysisApproach` text,
	`keyPhrases` json,
	`llmProvider` varchar(50) DEFAULT 'gemini',
	`llmModel` varchar(100) DEFAULT 'gemini-2.0-flash-exp',
	`isActive` boolean NOT NULL DEFAULT true,
	`isBuiltIn` boolean NOT NULL DEFAULT false,
	`displayOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `counselors_id` PRIMARY KEY(`id`),
	CONSTRAINT `counselors_counselorId_unique` UNIQUE(`counselorId`)
);
